DROP TABLE `quotes`;

CREATE TABLE `quotes` (
  `idquotes` int NOT NULL AUTO_INCREMENT,
  `underlying_symbol` varchar(16) NOT NULL,
  `quote_date` date NOT NULL,
  `root` varchar(16) NOT NULL,
  `expiration` date NOT NULL,
  `strike` float NOT NULL,
  `option_type` varchar(1) NOT NULL,
  `open` float NOT NULL,
  `high` float NOT NULL,
  `low` float NOT NULL,
  `close` float NOT NULL,
  `trade_volume` int NOT NULL,
  `bid_size_1545` int NOT NULL,
  `bid_1545` float NOT NULL,
  `ask_size_1545` int NOT NULL,
  `ask_1545` float NOT NULL,
  `underlying_bid_1545` float NOT NULL,
  `underlying_ask_1545` float NOT NULL,
  `implied_underlying_price_1545` float NOT NULL,
  `active_underlying_price_1545` float NOT NULL,
  `implied_volatility_1545` float NOT NULL,
  `delta_1545` float NOT NULL,
  `gamma_1545` float NOT NULL,
  `theta_1545` float NOT NULL,
  `vega_1545` float NOT NULL,
  `rho_1545` float NOT NULL,
  `bid_size_eod` int NOT NULL,
  `bid_eod` float NOT NULL,
  `ask_size_eod` int NOT NULL,
  `ask_eod` float NOT NULL,
  `underlying_bid_eod` float NOT NULL,
  `underlying_ask_eod` float NOT NULL,
  `vwap` float NOT NULL,
  `open_interest` int NOT NULL,
  `delivery_code` varchar(64) DEFAULT NULL,
  PRIMARY KEY (`idquotes`),
  KEY `idx_quotes_quote_date` (`quote_date`),
  KEY `idx_quotes_expiration` (`expiration`),
  KEY `idx_quotes_option_type` (`option_type`),
  KEY `idx_quotes_strike` (`strike`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
