DROP TABLE IF EXISTS `quotes`;

CREATE TABLE `quotes` (
  `idquotes` int NOT NULL AUTO_INCREMENT,
  `underlying_symbol` varchar(16) NOT NULL,
  `quote_date` date NOT NULL,
  `root` varchar(16) NOT NULL,
  `expiration` date NOT NULL,
  `strike` float NOT NULL,
  `option_type` varchar(1) NOT NULL,
  `open` float NOT NULL,
  `high` float NOT NULL,
  `low` float NOT NULL,
  `close` float NOT NULL,
  `trade_volume` int NOT NULL,
  `bid_size_1545` int NOT NULL,
  `bid_1545` float NOT NULL,
  `ask_size_1545` int NOT NULL,
  `ask_1545` float NOT NULL,
  `underlying_bid_1545` float NOT NULL,
  `underlying_ask_1545` float NOT NULL,
  `implied_underlying_price_1545` float NOT NULL,
  `active_underlying_price_1545` float NOT NULL,
  `implied_volatility_1545` float NOT NULL,
  `delta_1545` float NOT NULL,
  `gamma_1545` float NOT NULL,
  `theta_1545` float NOT NULL,
  `vega_1545` float NOT NULL,
  `rho_1545` float NOT NULL,
  `bid_size_eod` int NOT NULL,
  `bid_eod` float NOT NULL,
  `ask_size_eod` int NOT NULL,
  `ask_eod` float NOT NULL,
  `underlying_bid_eod` float NOT NULL,
  `underlying_ask_eod` float NOT NULL,
  `vwap` float NOT NULL,
  `open_interest` int NOT NULL,
  `delivery_code` varchar(64) DEFAULT NULL,
  `mid_1545` float GENERATED ALWAYS AS (((`bid_1545` + `ask_1545`) / 2)) STORED,
  `underlying_mid_1545` float GENERATED ALWAYS AS (((`underlying_bid_1545` + `underlying_ask_1545`) / 2)) STORED,
  `mid_eod` float GENERATED ALWAYS AS (((`bid_eod` + `ask_eod`) / 2)) STORED,
  `underlying_mid_eod` float GENERATED ALWAYS AS (((`underlying_bid_eod` + `underlying_ask_eod`) / 2)) STORED,
  `dte` int GENERATED ALWAYS AS ((to_days(`expiration`) - to_days(`quote_date`))) STORED,
  `delta_binned_1545` int GENERATED ALWAYS AS ((round((`delta_1545` * 20),0) * 5)) STORED,
  PRIMARY KEY (`idquotes`),
  KEY `idx_quotes_underlying_symbol_quote_date` (`underlying_symbol`,`quote_date`),
  KEY `idx_quotes_underlying_symbol_expiration` (`underlying_symbol`,`expiration`),
  KEY `idx_quotes_underlying_symbol_quote_date_delta_binned_1545_dte` (`underlying_symbol`,`quote_date`,`delta_binned_1545`,`dte`)
) ENGINE=InnoDB AUTO_INCREMENT=14034289 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
