DROP TABLE IF EXISTS `trades`;

CREATE TABLE `trades` (
  `idtrades` int NOT NULL AUTO_INCREMENT,
  `idstrategies` int NOT NULL,
  `shares` int DEFAULT NULL,
  `entry_legA_idquotes` int DEFAULT NULL,
  `entry_legB_idquotes` int DEFAULT NULL,
  `entry_legC_idquotes` int DEFAULT NULL,
  `entry_legD_idquotes` int DEFAULT NULL,
  `exit_legA_idquotes` int DEFAULT NULL,
  `exit_legB_idquotes` int DEFAULT NULL,
  `exit_legC_idquotes` int DEFAULT NULL,
  `exit_legD_idquotes` int DEFAULT NULL,
  `max_drawdown` float NOT NULL DEFAULT '0',
  `pnl` float NOT NULL DEFAULT '0',
  PRIMARY KEY (`idtrades`),
  KEY `idstrategies_idx` (`idstrategies`),
  KEY `entry_legA_idquotes_idx` (`entry_legA_idquotes`),
  KEY `entry_legB_idquotes_idx` (`entry_legB_idquotes`),
  KEY `entry_legC_idquotes_idx` (`entry_legC_idquotes`),
  KEY `entry_legD_idquotes_idx` (`entry_legD_idquotes`),
  KEY `exit_legA_idquotes_idx` (`exit_legA_idquotes`),
  KEY `exit_legB_idquotes_idx` (`exit_legB_idquotes`),
  KEY `exit_legC_idquotes_idx` (`exit_legC_idquotes`),
  KEY `exit_legD_idquotes_idx` (`exit_legD_idquotes`),
  CONSTRAINT `entry_legA_idquotes` FOREIGN KEY (`entry_legA_idquotes`) REFERENCES `quotes` (`idquotes`),
  CONSTRAINT `entry_legB_idquotes` FOREIGN KEY (`entry_legB_idquotes`) REFERENCES `quotes` (`idquotes`),
  CONSTRAINT `entry_legC_idquotes` FOREIGN KEY (`entry_legC_idquotes`) REFERENCES `quotes` (`idquotes`),
  CONSTRAINT `entry_legD_idquotes` FOREIGN KEY (`entry_legD_idquotes`) REFERENCES `quotes` (`idquotes`),
  CONSTRAINT `exit_legA_idquotes` FOREIGN KEY (`exit_legA_idquotes`) REFERENCES `quotes` (`idquotes`),
  CONSTRAINT `exit_legB_idquotes` FOREIGN KEY (`exit_legB_idquotes`) REFERENCES `quotes` (`idquotes`),
  CONSTRAINT `exit_legC_idquotes` FOREIGN KEY (`exit_legC_idquotes`) REFERENCES `quotes` (`idquotes`),
  CONSTRAINT `exit_legD_idquotes` FOREIGN KEY (`exit_legD_idquotes`) REFERENCES `quotes` (`idquotes`),
  CONSTRAINT `idstrategies` FOREIGN KEY (`idstrategies`) REFERENCES `strategies` (`idstrategies`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
