DROP TABLE IF EXISTS `trades`;

CREATE TABLE `trades` (
  `idtrades` int NOT NULL AUTO_INCREMENT,
  `idstrategies` int NOT NULL,
  `shares` int DEFAULT NULL,
  `entry_leg0_idquotes` int DEFAULT NULL,
  `entry_leg1_idquotes` int DEFAULT NULL,
  `entry_leg2_idquotes` int DEFAULT NULL,
  `entry_leg3_idquotes` int DEFAULT NULL,
  `exit_leg0_idquotes` int DEFAULT NULL,
  `exit_leg1_idquotes` int DEFAULT NULL,
  `exit_leg2_idquotes` int DEFAULT NULL,
  `exit_leg3_idquotes` int DEFAULT NULL,
  `max_drawdown` float NOT NULL DEFAULT '0',
  `pnl` float NOT NULL DEFAULT '0',
  PRIMARY KEY (`idtrades`),
  KEY `idstrategies_idx` (`idstrategies`),
  KEY `entry_leg0_idquotes_idx` (`entry_leg0_idquotes`),
  KEY `entry_leg1_idquotes_idx` (`entry_leg1_idquotes`),
  KEY `entry_leg2_idquotes_idx` (`entry_leg2_idquotes`),
  KEY `entry_leg3_idquotes_idx` (`entry_leg3_idquotes`),
  KEY `exit_leg0_idquotes_idx` (`exit_leg0_idquotes`),
  KEY `exit_leg1_idquotes_idx` (`exit_leg1_idquotes`),
  KEY `exit_leg2_idquotes_idx` (`exit_leg2_idquotes`),
  KEY `exit_leg3_idquotes_idx` (`exit_leg3_idquotes`),
  CONSTRAINT `entry_leg0_idquotes` FOREIGN KEY (`entry_leg0_idquotes`) REFERENCES `quotes` (`idquotes`),
  CONSTRAINT `entry_leg1_idquotes` FOREIGN KEY (`entry_leg1_idquotes`) REFERENCES `quotes` (`idquotes`),
  CONSTRAINT `entry_leg2_idquotes` FOREIGN KEY (`entry_leg2_idquotes`) REFERENCES `quotes` (`idquotes`),
  CONSTRAINT `entry_leg3_idquotes` FOREIGN KEY (`entry_leg3_idquotes`) REFERENCES `quotes` (`idquotes`),
  CONSTRAINT `exit_leg0_idquotes` FOREIGN KEY (`exit_leg0_idquotes`) REFERENCES `quotes` (`idquotes`),
  CONSTRAINT `exit_leg1_idquotes` FOREIGN KEY (`exit_leg1_idquotes`) REFERENCES `quotes` (`idquotes`),
  CONSTRAINT `exit_leg2_idquotes` FOREIGN KEY (`exit_leg2_idquotes`) REFERENCES `quotes` (`idquotes`),
  CONSTRAINT `exit_leg3_idquotes` FOREIGN KEY (`exit_leg3_idquotes`) REFERENCES `quotes` (`idquotes`),
  CONSTRAINT `idstrategies` FOREIGN KEY (`idstrategies`) REFERENCES `strategies` (`idstrategies`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
